# Reference prefixes for theorem environments

Format 49

IfStyle Teorema
	RefPrefix thm
End

IfStyle Corolario
	RefPrefix cor
End

IfStyle Lema
	RefPrefix lem
End

IfStyle Proposición
	RefPrefix prop
End

IfStyle Conjetura
	RefPrefix conj
End

IfStyle Definición
	RefPrefix def
End

IfStyle Ejemplo
	RefPrefix exa
End

IfStyle Problema
	RefPrefix prob
End

IfStyle Ejercicio
	RefPrefix exer
End

IfStyle Nota
	RefPrefix rem
End

IfStyle Claim
	RefPrefix claim
End

IfStyle Fact
	RefPrefix fact
End

IfStyle Criterio
	RefPrefix cri
End

IfStyle Algoritmo
	RefPrefix alg
End

IfStyle Axioma
	RefPrefix axm
End

IfStyle Condición
	RefPrefix cond
End

IfStyle Note
	RefPrefix note
End

IfStyle Notación
	RefPrefix nota
End

IfStyle Resumen
	RefPrefix sum
End

IfStyle Agradecimientos
	RefPrefix ack
End

IfStyle Conclusión
	RefPrefix conc
End

IfStyle Assumption
	RefPrefix assu
End
